<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="POU_SetStatus" Id="{04dac471-e342-4348-a3f6-e1eada599089}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU_SetStatus
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU_SetStatus">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>